# Generated by Django 5.1.6 on 2025-05-07 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_followed_question_designers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='followed_question_designers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_question_designer': True}, null=True, related_name='followers_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
