# Generated by Django 5.0.7 on 2025-01-21 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_admin_user_question_designer_user_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_question_desiner',
            new_name='is_question_designer',
        ),
        migrations.AlterField(
            model_name='question_designer',
            name='designer',
            field=models.ForeignKey(limit_choices_to={'is_question_designer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL),
        ),
    ]
