# Generated by Django 5.0.7 on 2025-01-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_question_desiner_customuser_is_question_designer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_question_designer',
            new_name='is_question_desiner',
        ),
    ]
