# Generated by Django 5.1.6 on 2025-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_followed_question_designers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='followed_question_designers',
        ),
    ]
