# Generated by Django 5.1.6 on 2025-05-20 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_student_followed_question_designers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_designer',
            name='followers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='followed_designers', to=settings.AUTH_USER_MODEL),
        ),
    ]
