# Generated by Django 5.1.6 on 2025-05-21 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_question_designer_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_designer',
            name='followers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
