# Generated by Django 5.1.6 on 2025-05-21 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_question_designer_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_designer',
            name='followers',
        ),
        migrations.AddField(
            model_name='student',
            name='following',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_question_designer': True}, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
