# Generated by Django 5.0.7 on 2025-02-24 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
