# Generated by Django 5.1.4 on 2024-12-20 01:27

import django.db.models.deletion
import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='question_audios/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_stage', models.ManyToManyField(related_name='subquestion', to='school.education_stage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestion', to='school.question')),
                ('question_desiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='account.question_designer')),
            ],
            options={
                'db_table': 'subquestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Right_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=school.models.right_answer_upload_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=school.models.right_answer_upload_path)),
                ('type', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('n', 'n')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_answer', to='school.subquestion')),
            ],
            options={
                'db_table': 'right_answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wrong_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=school.models.wrong_answer_upload_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=school.models.wrong_answer_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer', to='school.subquestion')),
            ],
            options={
                'db_table': 'wrong_answer',
                'ordering': ['-created_at'],
            },
        ),
    ]
