# Generated by Django 5.1.5 on 2025-02-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'کتاب ', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'دوره ', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='course_prerequisite',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیش نیاز دوره', 'verbose_name_plural': 'پیش نیاز های دوره'},
        ),
        migrations.AlterModelOptions(
            name='leitner',
            options={'ordering': ['-created_at'], 'verbose_name': 'لایتنر', 'verbose_name_plural': 'لایتنر ها'},
        ),
        migrations.AlterModelOptions(
            name='leitner_question',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'لایتنر، سوال'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'درس ', 'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['-created_at'], 'verbose_name': 'تمرین', 'verbose_name_plural': 'تمرین ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'صورت سوال', 'verbose_name_plural': 'صورت سوال'},
        ),
        migrations.AlterModelOptions(
            name='question_practice_worksheet',
            options={'ordering': ['-created_at'], 'verbose_name': 'کارنامه سوال تمرین', 'verbose_name_plural': 'کارنامه های سوال،تمرین'},
        ),
        migrations.AlterModelOptions(
            name='right_answer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'جواب های درست'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_at'], 'verbose_name': 'فصل ', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسانه', 'verbose_name_plural': 'رسانه'},
        ),
        migrations.AlterModelOptions(
            name='social_subject',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'موضوع/رسانه'},
        ),
        migrations.AlterModelOptions(
            name='study_report',
            options={'ordering': ['-created_at'], 'verbose_name': 'کارنامه مطالعه', 'verbose_name_plural': 'کارنامه های مطالعاتی'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'موضوع ', 'verbose_name_plural': 'موضوع ها'},
        ),
        migrations.AlterModelOptions(
            name='subquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوال ها'},
        ),
        migrations.AlterModelOptions(
            name='wrong_answer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'جواب های غلط'},
        ),
    ]
