# Generated by Django 5.1.4 on 2024-12-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_question_subquestion_right_answer_wrong_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'صورت سوال'},
        ),
        migrations.AlterModelOptions(
            name='subquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال'},
        ),
        migrations.AddField(
            model_name='social',
            name='educational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='introduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='tip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
