# Generated by Django 5.0.7 on 2025-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_book_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_practice_worksheet',
            old_name='needed_time',
            new_name='time_for_each_subquestion',
        ),
        migrations.RemoveField(
            model_name='question_practice_worksheet',
            name='time',
        ),
        migrations.AddField(
            model_name='question_practice_worksheet',
            name='subquestion',
            field=models.ManyToManyField(related_name='question_practice_worksheet', to='school.subquestion'),
        ),
    ]
