# Generated by Django 5.1.4 on 2024-12-20 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_question_options_alter_subquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subquestion_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrong_answer',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer', to='school.subject'),
        ),
        migrations.AlterField(
            model_name='social',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subquestion', to='school.question'),
        ),
    ]
