# Generated by Django 5.0.7 on 2025-03-01 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_leitner_datel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 2, 28)),
        ),
    ]
