# Generated by Django 5.0.7 on 2025-02-05 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_needed_time_question_practice_worksheet_time_for_each_subquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
