# Generated by Django 4.2.11 on 2025-01-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_admin_user_question_designer_user_student_user_and_more'),
        ('school', '0004_subquestion_image_subquestion_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_designer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questionss', to='account.question_designer'),
            preserve_default=False,
        ),
    ]
