# Generated by Django 5.0.7 on 2025-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_subquestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='time',
            field=models.DurationField(),
        ),
    ]
