# Generated by Django 5.0.7 on 2025-02-22 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_question_exam_subquestion_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='exam',
        ),
        migrations.AlterField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 2, 21)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 22)),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
