# Generated by Django 5.0.7 on 2025-02-05 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_subquestion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='time',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
