# Generated by Django 5.1.5 on 2025-01-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_question_question_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_designer',
        ),
    ]
