# Generated by Django 5.0.7 on 2025-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_subquestion_exam_alter_leitner_datel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
