# Generated by Django 5.0.7 on 2025-02-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_subquestion_time_subquestion_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='duration',
            new_name='time',
        ),
    ]
