# Generated by Django 5.1.5 on 2025-01-15 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_question_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_stage',
            name='desiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_stage', to=settings.AUTH_USER_MODEL),
        ),
    ]
