# Generated by Django 5.1.6 on 2025-05-20 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_leitner_datel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 5, 19)),
        ),
    ]
