# Generated by Django 5.0.7 on 2025-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_question_practice_worksheet_subquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_practice_worksheet',
            name='time_for_each_subquestion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question_practice_worksheet',
            name='time_spent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='study_report',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
