# Generated by Django 5.1.6 on 2025-07-04 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_question_designer_followers_student_following'),
        ('school', '0009_alter_leitner_datel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 7, 3)),
        ),
        migrations.AlterField(
            model_name='right_answer',
            name='type',
            field=models.CharField(blank=True, choices=[('-1', '-1'), ('0', '0'), ('n', 'n')], max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='practice',
            constraint=models.UniqueConstraint(fields=('student', 'subquestion'), name='unique_student_subquestion'),
        ),
    ]
