# Generated by Django 5.1.5 on 2025-01-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_education_stage_designer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='right_answer',
            old_name='question',
            new_name='subquestion',
        ),
        migrations.RenameField(
            model_name='wrong_answer',
            old_name='question',
            new_name='subquestion',
        ),
    ]
