# Generated by Django 5.1.5 on 2025-02-10 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_phone'),
        ('school', '0010_rename_time_for_each_subquestion_question_practice_worksheet_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 2, 9)),
        ),
        migrations.AddField(
            model_name='leitner_question',
            name='datelq',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leitner',
            name='last_step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leitner',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner', to='account.student'),
        ),
        migrations.AlterField(
            model_name='leitner_question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_question', to='account.student'),
        ),
        migrations.AlterField(
            model_name='leitner_question',
            name='subquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_question', to='school.subquestion'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='question_practice_worksheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
