# Generated by Django 5.1.6 on 2025-07-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_leitner_datel_alter_right_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practice',
            name='unique_student_subquestion',
        ),
    ]
