# Generated by Django 5.1.6 on 2025-11-03 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_practice_unique_student_subquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner',
            name='datel',
            field=models.DateField(default=datetime.date(2025, 11, 2)),
        ),
    ]
