# Generated by Django 5.1.5 on 2025-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_leitner_datel_leitner_question_datelq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='n',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
