# Generated by Django 5.1.5 on 2025-01-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_admin_user_remove_question_designer_user_and_more'),
        ('school', '0011_rename_question_right_answer_subquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درس ها',
                'db_table': 'lesson',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='education_stage',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='education_stage',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'موضوع ها'},
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
        migrations.AddField(
            model_name='social_subject',
            name='category',
            field=models.CharField(choices=[('Course', 'Course'), ('Book', 'Book'), ('Season', 'Season'), ('Lesson', 'Lesson'), ('Subject', 'Subject')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='account.question_designer')),
            ],
            options={
                'verbose_name': 'دوره ها',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='school.course')),
            ],
            options={
                'verbose_name': 'کتاب ها',
                'db_table': 'book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.lesson'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='school.book')),
            ],
            options={
                'verbose_name': 'فصل ها',
                'db_table': 'season',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.season'),
        ),
        migrations.DeleteModel(
            name='Education_stage',
        ),
    ]
