# Generated by Django 5.1.5 on 2025-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_lesson_remove_subject_education_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='subject',
            field=models.ManyToManyField(related_name='subquestion', to='school.subject'),
        ),
    ]
