# Generated by Django 5.1.5 on 2025-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_subquestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='category',
            field=models.CharField(choices=[('Course', 'Course'), ('Book', 'Book'), ('Season', 'Season'), ('Lesson', 'Lesson'), ('Subject', 'Subject')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
