# Generated by Django 5.1.5 on 2025-01-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_subquestion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='category',
        ),
        migrations.AddField(
            model_name='social_subject',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social_subject', to='school.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_subject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_subject', to='school.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_subject',
            name='lesson',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social_subject', to='school.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_subject',
            name='season',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='social_subject', to='school.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_subject',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='social_subject', to='school.subject'),
            preserve_default=False,
        ),
    ]
