# Generated by Django 5.1.5 on 2025-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_social_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='subquestions', to='school.book'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='subquestions', to='school.course'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='subquestions', to='school.lesson'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='season',
            field=models.ManyToManyField(blank=True, null=True, related_name='subquestions', to='school.season'),
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='book',
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='season',
        ),
        migrations.RemoveField(
            model_name='social_subject',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='subquestions', to='school.subject'),
        ),
        migrations.AddField(
            model_name='social_subject',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_subject', to='school.book'),
        ),
        migrations.AddField(
            model_name='social_subject',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_subject', to='school.course'),
        ),
        migrations.AddField(
            model_name='social_subject',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_subject', to='school.lesson'),
        ),
        migrations.AddField(
            model_name='social_subject',
            name='season',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_subject', to='school.season'),
        ),
        migrations.AddField(
            model_name='social_subject',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_subject', to='school.subject'),
        ),
    ]
