# Generated by Django 5.0.7 on 2025-01-31 19:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_admin_user_remove_question_designer_user_and_more'),
        ('school', '0016_subquestion_book_subquestion_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_subject',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='social_subject', to='school.book'),
        ),
        migrations.AlterField(
            model_name='social_subject',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='social_subject', to='school.course'),
        ),
        migrations.AlterField(
            model_name='social_subject',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='social_subject', to='school.lesson'),
        ),
        migrations.AlterField(
            model_name='social_subject',
            name='season',
            field=models.ManyToManyField(blank=True, related_name='social_subject', to='school.season'),
        ),
        migrations.AlterField(
            model_name='social_subject',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='social_subject', to='school.subject'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='school.book'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='school.course'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='school.lesson'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='season',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='school.season'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='school.subject'),
        ),
        migrations.CreateModel(
            name='Course_prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisits', to='school.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisite', to='school.course')),
            ],
            options={
                'verbose_name': 'پیش نیاز دوره',
                'db_table': 'course_prerequisite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leitner_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Leitner_question', to='account.student')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Leitner_question', to='school.subquestion')),
            ],
            options={
                'verbose_name': 'لایتنر، سوال',
                'db_table': 'leitner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Littler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_step', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Littler', to='account.student')),
            ],
            options={
                'verbose_name': 'لایتنر',
                'db_table': 'littler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero', models.PositiveIntegerField(default=0)),
                ('nf', models.PositiveIntegerField(default=0)),
                ('nt', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(to='account.student')),
                ('subquestions', models.ManyToManyField(to='school.subquestion')),
            ],
            options={
                'verbose_name': 'تمرین',
                'db_table': 'practice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question_practice_worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_time', models.DurationField(default=datetime.timedelta(0))),
                ('time', models.DurationField(default=datetime.timedelta(0))),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_practice_worksheet', to='account.student')),
            ],
            options={
                'verbose_name': 'کارنامه سوال تمرین',
                'db_table': 'question_practice_worksheet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Study_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_report', to='school.social')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_report', to='account.student')),
            ],
            options={
                'verbose_name': 'کارنامه مطالعه',
                'db_table': 'study_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
